# Generated by Django 3.0 on 2020-05-09 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='profile_imgs/profile_defualt.png', upload_to='profile_imgs')),
                ('bio', models.TextField(blank=True, max_length=200, null=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='number_followers', to='ProfileApp.Profile')),
                ('following', models.ManyToManyField(blank=True, related_name='Following', to='ProfileApp.Profile')),
                ('posts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Post')),
                ('profile_stories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Story')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('follower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('influncer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influncer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
